Repository talkpick/talkpick-frontend, pull requests merged in 2025-05, with the labels that each got.

#30 Fix/#27 뉴스 상세 조회 오류 수정
  src/app/(auth)/login/page.js
  src/app/(auth)/signup/page.js
  src/app/api/auth/auth.js
  src/app/api/news/[id]/newsDetailApi.js
  src/app/api/search/route.js
  src/app/news/[id]/page.js
  src/app/search/page.js
  src/components/PasswordToggleIcon.jsx
Labels: enhancement

#37 🚀 Deploy: MVP 모델 배포 (v0.0.1)
  .github/workflows/talkpick-frontend-deploy.yml
  .gitignore
  README.md
  eslint.config.mjs
  jsconfig.json
  next.config.js
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/file.svg
  public/globe.svg
  public/icon_new.svg
  public/logo_horizental.svg
  public/logo_vertical.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/(auth)/login/page.js
  src/app/(auth)/signup/page.js
  src/app/(auth)/signup/signUpValidator.js
  src/app/(temp)/chat/[newsId]/page.js
  src/app/Providers.jsx
  src/app/api/auth/auth.js
  src/app/api/news/detail/[id]/newsDetailApi.js
  src/app/api/news/newsListApi.js
  src/app/api/search/searchApi.js
  src/app/dashboard/page.js
  src/app/globals.css
  src/app/layout.js
  src/app/news/detail/[id]/page.js
  src/app/not-found.js
  src/app/page.js
  src/app/search/page.js
  src/components/BaseHeader.js
  src/components/Footer.js
  src/components/Header.js
  src/components/SearchBar.js
  src/components/icons/ChevronDownIcon.js
  src/components/icons/PasswordToggleIcon.js
  src/components/icons/SearchIcon.js
  src/components/icons/XIcon.js
  src/components/news/NewsCarousel.js
  src/components/news/NewsList.js
  src/constants/categories.js
  src/contexts/AuthContext.js
  src/hooks/useAuth.js
  src/lib/axios.js
  src/lib/requestValidators.js
  src/lib/socket.js
  src/lib/utils.js
Labels: 배포, D-1

#44 ✨ Feature/#42 회원 부가 기능 개발
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/talkpick-frontend.iml
  .idea/vcs.xml
  src/app/(auth)/login/page.js
  src/app/(auth)/recovery/account/page.js
  src/app/(auth)/recovery/password/page.js
  src/app/(auth)/signup/page.js
  src/app/api/auth/auth.js
  src/app/user/page.js
  src/components/BaseHeader.js
Labels: D-1
